# Generated by Django 5.0.4 on 2024-06-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='continente',
            name='descripcion_continente',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Descripcion continente'),
        ),
    ]
