# Generated by Django 5.0.4 on 2024-06-08 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoIdioma', models.CharField(max_length=10, unique=True, verbose_name='Codigo Idioma')),
                ('idioma', models.CharField(max_length=20, unique=True, verbose_name='Nombre Idioma')),
                ('idioma_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pais.pais')),
            ],
        ),
    ]
