# Generated by Django 5.0.4 on 2024-06-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoPais', models.CharField(max_length=10, unique=True, verbose_name='Codigo Pais')),
                ('nombrePais', models.CharField(max_length=30, unique=True, verbose_name='Nombre Pais')),
                ('descripcionPais', models.CharField(max_length=30, unique=True, verbose_name='Descripcion del Pais')),
            ],
        ),
    ]
